// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzerk5zTGXopu4sQR6wv0WoA1C9IegwNg',
    appId: '1:348696503982:android:710872f26a2dea85cbaf3f',
    messagingSenderId: '348696503982',
    projectId: 'mini-project-mobile-app-12b8e',
    databaseURL: 'https://mini-project-mobile-app-12b8e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mini-project-mobile-app-12b8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOZ_ePRwdlPB8bQZ8vJv65w70N4CyQgow',
    appId: '1:348696503982:ios:6726367821d33041cbaf3f',
    messagingSenderId: '348696503982',
    projectId: 'mini-project-mobile-app-12b8e',
    databaseURL: 'https://mini-project-mobile-app-12b8e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mini-project-mobile-app-12b8e.appspot.com',
    iosBundleId: 'com.example.miniProject',
  );
}
